# Generated by Django 5.0 on 2023-12-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(default=0, verbose_name='telefono')),
                ('asunto', models.CharField(max_length=40, verbose_name='Asunto')),
                ('mensaje', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Motivo de contacto',
                'verbose_name_plural': 'Motivos de contacto',
                'ordering': ['-creacion'],
            },
        ),
    ]
