# Generated by Django 5.0 on 2023-12-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('educacion', models.TextField(verbose_name='Estudios')),
                ('ExperienciaLaboral', models.TextField(verbose_name='Experiencia laboral')),
                ('image', models.ImageField(upload_to='datosusuarios', verbose_name='imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion')),
                ('actualizacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Datos de usuario',
                'verbose_name_plural': 'Datos de los Usuarios',
                'ordering': ['-creacion'],
            },
        ),
    ]
