# Generated by Django 5.0 on 2023-12-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuariodatos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodatos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='datosusuarios', verbose_name='imagen'),
        ),
    ]
