# Generated by Django 5.0 on 2023-12-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuariodatos_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioDatos',
        ),
    ]
