# Generated by Django 5.0 on 2023-12-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0004_delete_usuariodatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('acercaDeMi', models.TextField()),
                ('capacitaciones', models.TextField()),
                ('image', models.ImageField(upload_to='datosusuarios', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacio')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Datos de Usuario',
                'verbose_name_plural': 'Datos de usuarios',
                'ordering': ['-creacion'],
            },
        ),
    ]
