# Generated by Django 5.0 on 2023-12-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuariodato_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodato',
            name='email',
            field=models.EmailField(default='none', max_length=20, verbose_name='correo electronico.'),
        ),
    ]
