# Generated by Django 5.0 on 2023-12-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuariodato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodato',
            name='email',
            field=models.EmailField(default='none', max_length=30, verbose_name='correo electronico.'),
        ),
    ]
