# Generated by Django 4.1.5 on 2023-12-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuariodato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodato',
            name='image',
            field=models.ImageField(blank=True, default='static/usuario/img/Imagen-en-blanco.jpg', null=True, upload_to='datosusuarios', verbose_name='Imagen'),
        ),
    ]
