# Generated by Django 4.1.5 on 2023-12-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_usuariodato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodato',
            name='email',
            field=models.EmailField(blank=True, default='none', max_length=30, null=True, verbose_name='correo electronico.'),
        ),
    ]
