# Generated by Django 4.1.5 on 2023-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuariodato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodato',
            name='email',
            field=models.EmailField(blank=True, default='none@tumail.com', max_length=30, null=True, verbose_name='correo electronico.'),
        ),
        migrations.AlterField(
            model_name='usuariodato',
            name='image',
            field=models.ImageField(blank=True, default='media\\datosusuarios\\Imagen-en-blanco.jpg', null=True, upload_to='datosusuarios', verbose_name='Imagen'),
        ),
    ]
