# Generated by Django 5.0 on 2023-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_usuariodato_email_alter_usuariodato_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodato',
            name='image',
            field=models.ImageField(blank=True, default='\\Imagen-en-blanco.jpg', null=True, upload_to='datosusuarios', verbose_name='Imagen'),
        ),
    ]
