# Generated by Django 5.0 on 2023-12-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField()),
                ('image', models.ImageField(upload_to='projectempresa', verbose_name='Imagen')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
        ),
    ]
