# Generated by Django 5.0 on 2023-12-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresadatos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEmpresa',
        ),
    ]
