# Generated by Django 5.0 on 2023-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_delete_projectempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresadatos',
            options={'ordering': ['-creacion'], 'verbose_name': 'Empresa Dato', 'verbose_name_plural': 'Empresa Datos'},
        ),
        migrations.AlterField(
            model_name='empresadatos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projectempresa', verbose_name='Imagen'),
        ),
    ]
