# Generated by Django 5.0 on 2023-12-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_empresadatos_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresadatos',
            name='email',
            field=models.EmailField(default='none', max_length=30, verbose_name='Correo de contacto.'),
        ),
    ]
