# Generated by Django 5.0 on 2023-12-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_empresadatos_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresadatos',
            name='email',
        ),
    ]
