# Generated by Django 5.0 on 2023-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_empresadatos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresadatos',
            name='image',
            field=models.ImageField(blank=True, default='\\image-empresa-defautl.png', null=True, upload_to='projectempresa', verbose_name='Imagen'),
        ),
    ]
